### ISSUE TITLE
Do not honor --with-xkbdconfig=/etc/X11/xorg.conf.d/10-keyboard.conf in configure, search for 30-keyboard.conf

### ISSUE THREAD

**Issue by Chevek** [lfs-book/blocaled#6]
Hi,
I installed blocaled on gentoo using this configure :
./configure --prefix=/usr --sysconfdir=/etc --with-localeconfig=/etc/env.d/02locale --with-keyboardconfig=/etc/conf.d/keymaps --with-xkbdconfig=/etc/X11/xorg.conf.d/10-keyboard.conf

when I did this step :
source /etc/conf.d/keymaps &&
KEYMAP=${KEYMAP:-fr}          &&

gdbus call --system                                             \
           --dest org.freedesktop.locale1                       \
           --object-path /org/freedesktop/locale1               \
           --method org.freedesktop.locale1.SetVConsoleKeyboard \
           "$KEYMAP" "$KEYMAP_CORRECTIONS" true true

I got an error complaining it could not find "30-keyboard.conf" (notice the 30, but in configure I setted it to "10-keyboard.conf")

Then I added this extra step before :
cp /etc/X11/xorg.conf.d/10-keyboard.conf /etc/X11/xorg.conf.d/30-keyboard.conf

And now the gdbus call works.

This is documented here :
https://github.com/wamuu-sudo/orchid/blob/main/testing/gdm-in-azerty.md

Regards

**Comment by pierre-labastie** [comment]
Have you checked the content of /etc/blocaled.conf?

The last line should be:
```
xkbdlayoutfile = /etc/X11/xorg.conf.d/10-keyboard.conf
```

**Comment by Chevek** [comment]
This is right.  I have that :
![image](https://user-images.githubusercontent.com/51275028/160246095-443635f7-a9b1-4ad4-9354-abcf8fb266a9.png)

**Comment by pierre-labastie** [comment]
Ok, thanks. I need to set up a VM to try to reproduce... Will take some time...

**Comment by Chevek** [comment]
If you read french, you can use our gentoo version, which should me much faster: 

https://github.com/wamuu-sudo/orchid/blob/main/Installation.md

**Comment by pierre-labastie** [comment]
Well, thanks (I can read French:) I found an already set up VM with artix. Let me try it

**Comment by pierre-labastie** [comment]
I cannot reproduce on artix... That is: it works. The gdbus command creates /etc/X11/xorg.conf.d/10-keyboard.conf.

**Comment by pierre-labastie** [comment]
I'll follow your tutorial for orchid and see what could go wrong there. Hmm, thinking of something: If you have openrc-settingsd installed, it may conflict with blocaled.

**Comment by Chevek** [comment]
It is indeed installed:
![image](https://user-images.githubusercontent.com/51275028/160248048-9bca2701-f6bf-42d6-8ca6-bdce47b383bf.png)

**Comment by pierre-labastie** [comment]
So you have two "localed" daemons installed, the one from openrc-settingsd, and teh one from blocaled. I suspect gdbus chose the openrc-settingsd one.

**Comment by Chevek** [comment]
Is blocaled able to fully replace openrc-settingsd? Or work with it?

**Comment by pierre-labastie** [comment]
It certainly can't replace openrc-settings, because there are 3 services in openrc-settingsd, and only one (the locale1 service) in blocaled. We have forked openrc-settingsd to remove the openrc specific parts (because we do not use it in linuxfromscratch). But we have also removed the other two services, because we do not need them.
I don't remember exactly how you can compile openrc-settingsd to use the configuration files you want, but you should be able to do that.

Once you convince openrc-settingsd to use 10-keyboard, I think the gdbus command can work without blocaled (using the locale1 service from openrc-settingsd). I do not like saying that, but with openrc installed, openrc-settingsd is enough and you do not need blocaled. Sigh :)

**Comment by pierre-labastie** [comment]
It appears that it is not blocaled that wanted to write in /etc/X11/xorg.conf.D/30-keayboard.conf, but openrc-settingsd. Closing

**Comment by Chevek** [comment]
Thank you *a lot* ! It worked as expected with openrc-settingsd.

Keep up the good work !
Best regards
